services:
  warehouse-management:
    image: warehouse-management
    build:
      context: .
      dockerfile: WarehouseManagement.WebAPI/Dockerfile
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=warehouse-management-db
    volumes:
      - warehouse-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
      
volumes:
  warehouse-db-data:

